version: '2'

networks:
  back-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: password
    networks:
      - back-tier
    volumes:
      - data:/data/db


  php:
    build: ./composeFiles/php
    container_name: php
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "80:80"
    environment:
      - XDEBUG_HOST=${XDEBUG_HOST}
    networks:
      - back-tier

volumes:
  data:
    driver: local
